"""Copying KPI targets to other periods."""

from odoo.exceptions import UserError
from odoo.tests import TransactionCase, tagged


@tagged('post_install', '-at_install')
class TestKpiTargetCopy(TransactionCase):

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.company = cls.env.company
        cls.kpi = cls.env['hr.kpi'].create({'name': 'Copy KPI', 'company_id': cls.company.id})
        cls.other_kpi = cls.env['hr.kpi'].create({'name': 'Other Copy KPI', 'company_id': cls.company.id})
        cls.Period = cls.env['hr.kpi.period']
        cls.Target = cls.env['hr.kpi.target']

    def _target(self, kpi, period, planned=100.0):
        return self.Target.create({
            'kpi_id': kpi.id, 'period_id': period.id, 'company_id': self.company.id,
            'planned_value': planned,
        })

    def _wizard(self, targets, **vals):
        return self.env['hr.kpi.target.copy.wizard'].with_context(
            active_model='hr.kpi.target', active_ids=targets.ids,
        ).create(vals)

    def test_next_period_is_suggested(self):
        q4 = self.Period._find_or_create('quarter', 2048, quarter='4', company=self.company)
        wizard = self._wizard(self._target(self.kpi, q4))
        self.assertEqual((wizard.period_type, wizard.period_year, wizard.period_quarter),
                         ('quarter', '2049', '1'))
        december = self.Period._find_or_create('month', 2048, month='12', company=self.company)
        wizard = self._wizard(self._target(self.other_kpi, december))
        self.assertEqual((wizard.period_type, wizard.period_year, wizard.period_month), ('month', '2049', '1'))

    def test_copy_quarter_to_each_quarter(self):
        q1 = self.Period._find_or_create('quarter', 2048, quarter='1', company=self.company)
        target = self._target(self.kpi, q1, planned=250.0)
        target.write({'actual_value': 90.0, 'state': 'confirmed'})
        for quarter in ('2', '3', '4'):
            wizard = self._wizard(target, period_type='quarter', period_year='2048', period_quarter=quarter)
            # Only the first quarter exists: each period is generated by its copy
            self.assertTrue(wizard.period_missing)
            action = wizard.action_copy()
            self.assertEqual(action['res_model'], 'hr.kpi.target')
        copies = self.Target.search([('kpi_id', '=', self.kpi.id), ('id', '!=', target.id)])
        self.assertEqual(sorted(copies.period_id.mapped('name')), ['2048-Q2', '2048-Q3', '2048-Q4'])
        for copy in copies:
            self.assertEqual((copy.planned_value, copy.actual_value, copy.state), (250.0, 0.0, 'draft'))

    def test_copy_without_planned_value_and_several_targets(self):
        january = self.Period._find_or_create('month', 2048, month='1', company=self.company)
        targets = self._target(self.kpi, january) | self._target(self.other_kpi, january)
        self._wizard(targets, period_type='month', period_year='2049', period_month='5',
                     copy_planned_value=False).action_copy()
        copies = self.Target.search([('period_id.name', '=', '2049-05')])
        self.assertEqual(copies.kpi_id, self.kpi | self.other_kpi)
        self.assertFalse(any(copies.mapped('planned_value')))

    def test_existing_and_overlapping_targets_are_skipped(self):
        q1 = self.Period._find_or_create('quarter', 2048, quarter='1', company=self.company)
        july = self.Period._find_or_create('month', 2048, month='7', company=self.company)
        targets = self._target(self.kpi, q1) | self._target(self.other_kpi, q1)
        self._target(self.kpi, july)
        result = self._wizard(targets, period_type='quarter', period_year='2048',
                              period_quarter='3').action_copy()
        self.assertEqual(result['tag'], 'display_notification')
        q3_targets = self.Target.search([('period_id.name', '=', '2048-Q3')])
        # The KPI with a July target is skipped, the other one is copied
        self.assertEqual(q3_targets.kpi_id, self.other_kpi)
        with self.assertRaises(UserError):
            self._wizard(targets[:1], period_type='quarter', period_year='2048',
                         period_quarter='1').action_copy()
